SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


create view [dbo].[vwDailyUpdSlct_PoClsd_8]
as
SELECT vwDailyUpdslct_poclsd_7.catalog, 
       vwDailyUpdslct_poclsd_7.[catalog desc], 
       vwDailyUpdslct_poclsd_7.[po #], 
       vwDailyUpdslct_poclsd_7.[req #], 
       vwDailyUpdslct_poclsd_7.ndc, 
       vwDailyUpdslct_poclsd_7.[fiscal wk], 
       vwDailyUpdslct_poclsd_7.[fiscal month #], 
       vwDailyUpdslct_poclsd_7.[fiscal month], 
       vwDailyUpdslct_poclsd_7.[fiscal year], 
       mktbl_arrivals.exp_ship_date       AS [SHIP DATE], 
       vwDailyUpdslct_poclsd_7.[receipt date], 
       vwDailyUpdslct_poclsd_7.[original ndc], 
       vwDailyUpdslct_poclsd_7.[approved date], 
       vwDailyUpdslct_poclsd_7.[group code], 
       vwDailyUpdslct_poclsd_7.[merch type], 
       vwDailyUpdslct_poclsd_7.[style desc], 
       vwDailyUpdslct_poclsd_7.inv5, 
       vwDailyUpdslct_poclsd_7.[color desc], 
       vwDailyUpdslct_poclsd_7.inv7, 
       vwDailyUpdslct_poclsd_7.[size desc], 
       vwDailyUpdslct_poclsd_7.inv10, 
       vwDailyUpdslct_poclsd_7.[vendor #], 
       vwDailyUpdslct_poclsd_7.vendor, 
       vwDailyUpdslct_poclsd_7.[vendor style #], 
       vwDailyUpdslct_poclsd_7.[cost ea], 
       vwDailyUpdslct_poclsd_7.[po cost], 
       vwDailyUpdslct_poclsd_7.[orig ordered units], 
       vwDailyUpdslct_poclsd_7.[cxl units], 
       vwDailyUpdslct_poclsd_7.[oo units], 
       vwDailyUpdslct_poclsd_7.[oo cost], 
       vwDailyUpdslct_poclsd_7.[received units], 
       vwDailyUpdslct_poclsd_7.[received cost], 
       vwDailyUpdslct_poclsd_7.discounts, 
       vwDailyUpdslct_poclsd_7.chargeback, 
       vwDailyUpdslct_poclsd_7.terms, 
       vwDailyUpdslct_poclsd_7.[terms desc], 
       mktbl_arrivals.transportation_mode AS [SHIP MODE] 
FROM   vwDailyUpdslct_poclsd_7 
       LEFT JOIN mktbl_arrivals 
              ON vwDailyUpdslct_poclsd_7.[po #] = mktbl_arrivals.po_id 
GROUP  BY vwDailyUpdslct_poclsd_7.catalog, 
          vwDailyUpdslct_poclsd_7.[catalog desc], 
          vwDailyUpdslct_poclsd_7.[po #], 
          vwDailyUpdslct_poclsd_7.[req #], 
          vwDailyUpdslct_poclsd_7.ndc, 
          vwDailyUpdslct_poclsd_7.[fiscal wk], 
          vwDailyUpdslct_poclsd_7.[fiscal month #], 
          vwDailyUpdslct_poclsd_7.[fiscal month], 
          vwDailyUpdslct_poclsd_7.[fiscal year], 
          mktbl_arrivals.exp_ship_date, 
          vwDailyUpdslct_poclsd_7.[receipt date], 
          vwDailyUpdslct_poclsd_7.[original ndc], 
          vwDailyUpdslct_poclsd_7.[approved date], 
          vwDailyUpdslct_poclsd_7.[group code], 
          vwDailyUpdslct_poclsd_7.[merch type], 
          vwDailyUpdslct_poclsd_7.[style desc], 
          vwDailyUpdslct_poclsd_7.inv5, 
          vwDailyUpdslct_poclsd_7.[color desc], 
          vwDailyUpdslct_poclsd_7.inv7, 
          vwDailyUpdslct_poclsd_7.[size desc], 
          vwDailyUpdslct_poclsd_7.inv10, 
          vwDailyUpdslct_poclsd_7.[vendor #], 
          vwDailyUpdslct_poclsd_7.vendor, 
          vwDailyUpdslct_poclsd_7.[vendor style #], 
          vwDailyUpdslct_poclsd_7.[cost ea], 
          vwDailyUpdslct_poclsd_7.[po cost], 
          vwDailyUpdslct_poclsd_7.[orig ordered units], 
          vwDailyUpdslct_poclsd_7.[cxl units], 
          vwDailyUpdslct_poclsd_7.[oo units], 
          vwDailyUpdslct_poclsd_7.[oo cost], 
          vwDailyUpdslct_poclsd_7.[received units], 
          vwDailyUpdslct_poclsd_7.[received cost], 
          vwDailyUpdslct_poclsd_7.discounts, 
          vwDailyUpdslct_poclsd_7.chargeback, 
          vwDailyUpdslct_poclsd_7.terms, 
          vwDailyUpdslct_poclsd_7.[terms desc], 
          mktbl_arrivals.transportation_mode;
GO
