SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


Create view [dbo].[vwDailyUpdSlct_Inventory_1]
as 
SELECT Max(F21_FMSH_STOCK_ON_HAND.MS_VERSION_NO) AS MaxOfMS_VERSION_NO
FROM F21_FMSH_STOCK_ON_HAND
GO
