SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

Create view [dbo].[vwDailyUpdSlct_BackorderFill_1]
as 
SELECT F21_VDRS_ORDER_DETAIL.SKU, Sum(F21_VDRS_ORDER_DETAIL.QUANTITY) AS [BO UNITS], Sum(F21_VDRS_ORDER_DETAIL.EXT_COST) AS [BO COST $], Sum(F21_VDRS_ORDER_DETAIL.SH_REVENUE) AS [BO NET $], Sum(F21_VDRS_ORDER_DETAIL.EXT_PRICE) AS [BO TICKET $]
FROM F21_VDRS_ORDER_DETAIL
WHERE (((F21_VDRS_ORDER_DETAIL.CURRENT_STATUS)='BO'))
GROUP BY F21_VDRS_ORDER_DETAIL.SKU;
GO
