SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


Create view [dbo].[vwDailyUpdSlct_CatalogInventory]
as


SELECT  RefTbl_OPCSINET.[Cat#] AS [INET CATALOG], MkTbl_SKUMaster.CAT_DESCRIPTION AS DEPARTMENT, MkTbl_SKUMaster.SUBCAT_DESCRIPTION AS CLASS, MkTbl_SKUMaster.[STYLE DESCRIPTION], MkTbl_SKUMaster.[Offer Product Id] AS INV5, MkTbl_SKUMaster.[COLOR DESCRIPTION], Left([SKU],7) AS INV7, MkTbl_SKUMaster.[SIZE DESCRIPTION], MkTbl_SKUMaster.Sku AS INV10, RefTbl_OPCSINET.Statuscd AS STATUS, RefTbl_OPCSINET.Cost AS [INET COST], RefTbl_OPCSINET.InetPricedd AS [INET PRICE], RefTbl_OPCSINET.Catpricedd AS [CAT PRICE], MkTbl_SKUMaster.[POS Date] AS [POS DATE]
FROM MkTbl_SKUMaster LEFT JOIN RefTbl_OPCSINET ON MkTbl_SKUMaster.Sku = RefTbl_OPCSINET.INETSKUSO
GROUP BY RefTbl_OPCSINET.[Cat#], MkTbl_SKUMaster.CAT_DESCRIPTION, MkTbl_SKUMaster.SUBCAT_DESCRIPTION, MkTbl_SKUMaster.[STYLE DESCRIPTION], MkTbl_SKUMaster.[Offer Product Id], MkTbl_SKUMaster.[COLOR DESCRIPTION], Left([SKU],7), MkTbl_SKUMaster.[SIZE DESCRIPTION], MkTbl_SKUMaster.Sku, RefTbl_OPCSINET.Statuscd, RefTbl_OPCSINET.Cost, RefTbl_OPCSINET.InetPricedd, RefTbl_OPCSINET.Catpricedd, MkTbl_SKUMaster.[POS Date]
HAVING ((Left([SKU],1)='2'))
GO
