CREATE TABLE [dbo].[F21_VFMSH_PO_REQ_DETAIL]
(
[COMPANY_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[REQUISITION_NO] [numeric] (8, 0) NOT NULL,
[LINE_NO] [numeric] (4, 0) NOT NULL,
[QTY] [numeric] (8, 0) NULL,
[COST_EA] [numeric] (10, 4) NULL,
[EXTENDED_COST] [numeric] (10, 2) NULL,
[PRODUCT_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTOR1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTOR2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTOR3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SKU] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OUR_DESCRIPTION] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VENDOR_PART_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PART_DESCRIPTION] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPECTED_RECEIPT_DATE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REQUISITION_DATE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOTAL_COST] [numeric] (12, 2) NULL,
[VENDOR_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATUS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRINTED_DATE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PO_SHIP_DATE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PO_SHIP_VIA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PO_CANCEL_AFTER_DATE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PO_FOB] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PO_VENDOR_EMAIL] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VENDOR_NAME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTACT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VEN_ADDRESS1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VEN_ADDRESS2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VEN_ADDRESS3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VEN_CITY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VEN_STATE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VEN_POSTAL_CODE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VEN_COUNTRY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TERMS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VEN_TELEPHONE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VEN_EXTENSION] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VEN_FAX] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CO_NAME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CO_ADDRESS1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CO_ADDRESS2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CO_ADDRESS3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CO_CITY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CO_STATE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CO_POSTAL_CODE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CO_COUNTRY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CO_MAIN_PHONE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CO_PO_PHONE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CO_FAX] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
