CREATE TABLE [dbo].[MkTbl_DailyDetail]
(
[DailyOrdDtlCtr] [numeric] (18, 0) NOT NULL IDENTITY(1, 1),
[Item_Date] [datetime] NULL,
[Fiscal_Wk] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Month] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Qtr] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fiscal_Year] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order Count] [int] NULL,
[Dmnd_Units] [float] NULL,
[Dmnd_Gross$] [float] NULL,
[Dmnd_Net$] [float] NULL,
[Dmnd_Cost$] [float] NULL,
[ImmCx_Units] [float] NULL,
[ImmCxl_Gross$] [float] NULL,
[ImmCxl_Net$] [float] NULL,
[ImmCxl_Cost$] [float] NULL,
[Cxl_Units] [float] NULL,
[Cxl_Gross$] [float] NULL,
[Cxl_Net$] [float] NULL,
[Cxl_Cost$] [float] NULL,
[Ship_Units] [float] NULL,
[Ship_Gross$] [float] NULL,
[Ship_Net$] [float] NULL,
[Ship_Cost$] [float] NULL,
[Rtn_Units] [float] NULL,
[Rtn_Gross$] [float] NULL,
[Rtn_Net$] [float] NULL,
[Rtn_Cost$] [float] NULL,
[Exch_Units] [float] NULL,
[Exch_Gross$] [float] NULL,
[Exch_Net$] [float] NULL,
[Exch_Cost$] [float] NULL,
[Net_Units] [float] NULL,
[Net_Gross$] [float] NULL,
[Net_Net$] [float] NULL,
[Net_Cost$] [float] NULL,
[Tax$] [float] NULL,
[ShipHnd$] [float] NULL,
[CrOn] [datetime] NULL CONSTRAINT [DF_MkTbl_DailyDetail_CrOn] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MkTbl_DailyDetail] ADD CONSTRAINT [PK_MkTbl_DailyDetail] PRIMARY KEY CLUSTERED  ([DailyOrdDtlCtr]) ON [PRIMARY]
GO
