CREATE TABLE [dbo].[F21_FMSH_ITEM_FORECAST_PERIOD]
(
[COMPANY_ID] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MS_VERSION_NO] [float] NOT NULL,
[SKU] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[WAREHOUSE_ID] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CALENDAR_SEQ] [float] NOT NULL,
[BEG_QOH_QTY] [float] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[F21_FMSH_ITEM_FORECAST_PERIOD] ADD CONSTRAINT [F21_FMSH_ITEM_FORECAST_PERIOD_PK] PRIMARY KEY CLUSTERED  ([COMPANY_ID], [MS_VERSION_NO], [SKU], [WAREHOUSE_ID], [CALENDAR_SEQ]) ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMSH_ITEM_FORECAST_PERIOD]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMSH_ITEM_FORECAST_PERIOD', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMSH_ITEM_FORECAST_PERIOD].[BEG_QOH_QTY]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMSH_ITEM_FORECAST_PERIOD', 'COLUMN', N'BEG_QOH_QTY'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMSH_ITEM_FORECAST_PERIOD].[CALENDAR_SEQ]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMSH_ITEM_FORECAST_PERIOD', 'COLUMN', N'CALENDAR_SEQ'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMSH_ITEM_FORECAST_PERIOD].[COMPANY_ID]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMSH_ITEM_FORECAST_PERIOD', 'COLUMN', N'COMPANY_ID'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMSH_ITEM_FORECAST_PERIOD].[MS_VERSION_NO]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMSH_ITEM_FORECAST_PERIOD', 'COLUMN', N'MS_VERSION_NO'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMSH_ITEM_FORECAST_PERIOD].[SKU]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMSH_ITEM_FORECAST_PERIOD', 'COLUMN', N'SKU'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMSH_ITEM_FORECAST_PERIOD].[WAREHOUSE_ID]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMSH_ITEM_FORECAST_PERIOD', 'COLUMN', N'WAREHOUSE_ID'
GO
