CREATE TABLE [dbo].[tmpVdrsOrdDtl]
(
[COMPANY_ID] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIVISION_ID] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORDER_NO] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORDER_LINE] [float] NULL,
[OFFER_ID] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OFFER_YEAR] [float] NULL,
[KEY_CODE] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORDER_DATE] [datetime2] (0) NULL,
[ORIG_DIVISION_ID] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORIG_OFFER_ID] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CALENDAR_SEQ] [float] NULL,
[PRODUCT_ID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORIG_OFFER_YEAR] [float] NULL,
[DESCRIPTOR1] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTOR2] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTOR3] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SKU] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEMAND_FROM] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEMAND_TYPE] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTOMER_SOLD] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTOMER_SHIP] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QUANTITY] [float] NULL,
[EXT_PRICE] [float] NULL,
[EXT_COST] [float] NULL,
[CURRENT_STATUS] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BO_DATE] [datetime2] (0) NULL,
[CANCEL_DATE] [datetime2] (0) NULL,
[SHIP_DATE] [datetime2] (0) NULL,
[CREATED_DATETIME] [datetime2] (0) NULL,
[LAST_UPDATED_DATETIME] [datetime2] (0) NULL,
[LAST_UPDATED_BY] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SH_COST] [float] NULL,
[SH_REVENUE] [float] NULL,
[SHIP_METHOD] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAY_METHOD] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CANCEL_QUANTITY] [float] NULL,
[SHIP_QUANTITY] [float] NULL,
[TOTAL_CREDIT] [float] NULL,
[SALESPERSON] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LIST_PRICE] [float] NULL,
[SHIP_REFERENCE_NO] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUBSTITUTED_SKU] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTOMER_DECISION] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTOMER_SITE] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTOMER_PAYER] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FUTURE_SHIP_DATE] [datetime2] (0) NULL,
[UNUSUAL_DEMAND_STATUS] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ALTERNATE_KEY_CODE] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RETURN_DATE] [datetime2] (0) NULL,
[RETURN_QUANTITY] [float] NULL,
[RESELLABLE_QUANTITY] [float] NULL,
[RETURN_CODE] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RETURN_ACTION] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RETURN_SH_COST] [float] NULL,
[RETURN_SH_REVENUE] [float] NULL,
[ALTERNATE_TRACKING_ID] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ALTERNATE_TRACKING_ORDER_LINE] [float] NULL,
[SALES_TAX_REFUND] [float] NULL,
[RESTOCK_CHARGE] [float] NULL,
[RETURN_SALESPERSON] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RETURN_TOTAL_CREDIT] [float] NULL,
[SKU_STATUS] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COST_EA] [float] NULL,
[STD_PRICE_EA] [float] NULL,
[STD_COST_EA] [float] NULL,
[SUB_CATEGORY_ID] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CATEGORY_ID] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEFAULT_VENDOR_ID] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BUYER] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCHEDULER] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRODUCT_ENGINEER] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DROP_SHIP_FLAG] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLASS_CODE] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER1] [float] NULL,
[USER2] [float] NULL,
[USER3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER4] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER5] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER6] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER7] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER8] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VENDOR_NAME] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CATEGORY_DESC] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUBCATEGORY_DESC] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SKU_DESCRIPTION] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRODUCT_DESCRIPTION] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WAREHOUSE_DEMAND] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WAREHOUSE_SHIPPED] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
