CREATE TABLE [dbo].[F21_FMKT_OFFER]
(
[COMPANY_ID] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DIVISION_ID] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OFFER_ID] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OFFER_YEAR] [float] NOT NULL,
[DESCRIPTION] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VEHICLE_ID] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SEASON_ID] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEDIA_ID] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER1] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER2] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER3] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER4] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MACRO_ORDERS_CURVE] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MACRO_UNITS_CURVE] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MACRO_REVENUE_CURVE] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MACRO_CIRCULATION] [float] NULL,
[MACRO_PERCENT_RESPONSE] [float] NULL,
[MACRO_REVENUE_ORDER] [float] NULL,
[MACRO_UNITS_ORDER] [float] NULL,
[MACRO_ORDERS] [float] NULL,
[MACRO_UNITS] [float] NULL,
[MACRO_REVENUE] [float] NULL,
[MACRO_UNUSUAL_DEMAND_REVENUE] [float] NULL,
[OFFER_VERSION_FLAG] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POST_ALL_FLAG] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ANTICIPATED_DROP_DATE] [datetime] NULL,
[AUTO_PROJ_PERCENT] [float] NULL,
[CREATED_DATETIME] [datetime] NULL,
[ACTUAL_DROP_DATE] [datetime] NULL,
[LAST_UPDATED_DATETIME] [datetime] NULL,
[ANTICIPATED_PERIOD_1_DATE] [datetime] NULL,
[LAST_UPDATED_BY] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTUAL_PERIOD_1_DATE] [datetime] NULL,
[PERIOD_1_ORDER_THRESHOLD] [float] NULL,
[PAGES] [float] NULL,
[CURRENT_PERIOD] [float] NULL,
[VERTICAL] [float] NULL,
[PERCENT_COMPLETE] [float] NULL,
[HORIZONTAL] [float] NULL,
[START_PERIOD] [float] NULL,
[START_THRESHOLD] [float] NULL,
[END_PERIOD] [float] NULL,
[END_THRESHOLD] [float] NULL,
[ANTICIPATED_END_DATE] [datetime] NULL,
[ACTUAL_END_DATE] [datetime] NULL,
[USE_AUTO_PROJ_PERCENT] [float] NULL,
[AUTO_PROJ_PERCENT_COMPLETE] [float] NULL,
[OFFER_COST] [float] NULL,
[OFFER_TYPE] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PLAN_STATUS] [float] NULL,
[IM_COST_LOCK_DATE] [datetime] NULL,
[FORECAST_VERSION_TYPE] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOLERANCE_PERCENT] [float] NULL,
[ALLOW_ZERO_FORECAST_FLAG] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VALIDATE_CRITERIA] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VALIDATE_LEVEL] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTIVE_OFFER_FLAG] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROJ_PUBLISH_CODE] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUTO_PROJ_METHOD] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUTO_PROJ_SKU_PERCENT] [float] NULL,
[RESEARCH_FLAG] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXCLUDE_FROM_LOOKBACK_FLAG] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOOKBACK_PRIORITY] [float] NULL,
[LINK_DIVISION_ID] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LINK_OFFER_ID] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LINK_OFFER_YEAR] [float] NULL,
[LINK_METRIC] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LINK_PUBLISH_FLAG] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LINK_STATUS_INFO] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MACRO_SHIP_CURVE] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ALLOCATION_SET_CODE] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[F21_FMKT_OFFER] ADD CONSTRAINT [F21_FMKT_OFFER_PK] PRIMARY KEY CLUSTERED  ([COMPANY_ID], [DIVISION_ID], [OFFER_ID], [OFFER_YEAR]) ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[ACTIVE_OFFER_FLAG]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'ACTIVE_OFFER_FLAG'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[ACTUAL_DROP_DATE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'ACTUAL_DROP_DATE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[ACTUAL_END_DATE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'ACTUAL_END_DATE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[ACTUAL_PERIOD_1_DATE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'ACTUAL_PERIOD_1_DATE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[ALLOCATION_SET_CODE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'ALLOCATION_SET_CODE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[ALLOW_ZERO_FORECAST_FLAG]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'ALLOW_ZERO_FORECAST_FLAG'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[ANTICIPATED_DROP_DATE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'ANTICIPATED_DROP_DATE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[ANTICIPATED_END_DATE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'ANTICIPATED_END_DATE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[ANTICIPATED_PERIOD_1_DATE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'ANTICIPATED_PERIOD_1_DATE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[AUTO_PROJ_METHOD]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'AUTO_PROJ_METHOD'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[AUTO_PROJ_PERCENT]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'AUTO_PROJ_PERCENT'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[AUTO_PROJ_PERCENT_COMPLETE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'AUTO_PROJ_PERCENT_COMPLETE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[AUTO_PROJ_SKU_PERCENT]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'AUTO_PROJ_SKU_PERCENT'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[COMPANY_ID]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'COMPANY_ID'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[CREATED_DATETIME]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'CREATED_DATETIME'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[CURRENT_PERIOD]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'CURRENT_PERIOD'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[DESCRIPTION]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'DESCRIPTION'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[DIVISION_ID]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'DIVISION_ID'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[END_PERIOD]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'END_PERIOD'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[END_THRESHOLD]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'END_THRESHOLD'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[EXCLUDE_FROM_LOOKBACK_FLAG]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'EXCLUDE_FROM_LOOKBACK_FLAG'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[FORECAST_VERSION_TYPE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'FORECAST_VERSION_TYPE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[HORIZONTAL]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'HORIZONTAL'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[IM_COST_LOCK_DATE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'IM_COST_LOCK_DATE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[LAST_UPDATED_BY]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'LAST_UPDATED_BY'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[LAST_UPDATED_DATETIME]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'LAST_UPDATED_DATETIME'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[LINK_DIVISION_ID]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'LINK_DIVISION_ID'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[LINK_METRIC]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'LINK_METRIC'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[LINK_OFFER_ID]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'LINK_OFFER_ID'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[LINK_OFFER_YEAR]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'LINK_OFFER_YEAR'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[LINK_PUBLISH_FLAG]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'LINK_PUBLISH_FLAG'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[LINK_STATUS_INFO]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'LINK_STATUS_INFO'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[LOOKBACK_PRIORITY]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'LOOKBACK_PRIORITY'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[MACRO_CIRCULATION]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'MACRO_CIRCULATION'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[MACRO_ORDERS]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'MACRO_ORDERS'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[MACRO_ORDERS_CURVE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'MACRO_ORDERS_CURVE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[MACRO_PERCENT_RESPONSE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'MACRO_PERCENT_RESPONSE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[MACRO_REVENUE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'MACRO_REVENUE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[MACRO_REVENUE_CURVE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'MACRO_REVENUE_CURVE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[MACRO_REVENUE_ORDER]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'MACRO_REVENUE_ORDER'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[MACRO_SHIP_CURVE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'MACRO_SHIP_CURVE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[MACRO_UNITS]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'MACRO_UNITS'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[MACRO_UNITS_CURVE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'MACRO_UNITS_CURVE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[MACRO_UNITS_ORDER]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'MACRO_UNITS_ORDER'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[MACRO_UNUSUAL_DEMAND_REVENUE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'MACRO_UNUSUAL_DEMAND_REVENUE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[MEDIA_ID]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'MEDIA_ID'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[OFFER_COST]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'OFFER_COST'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[OFFER_ID]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'OFFER_ID'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[OFFER_TYPE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'OFFER_TYPE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[OFFER_VERSION_FLAG]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'OFFER_VERSION_FLAG'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[OFFER_YEAR]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'OFFER_YEAR'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[PAGES]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'PAGES'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[PERCENT_COMPLETE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'PERCENT_COMPLETE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[PERIOD_1_ORDER_THRESHOLD]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'PERIOD_1_ORDER_THRESHOLD'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[PLAN_STATUS]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'PLAN_STATUS'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[POST_ALL_FLAG]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'POST_ALL_FLAG'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[PROJ_PUBLISH_CODE]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'PROJ_PUBLISH_CODE'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[RESEARCH_FLAG]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'RESEARCH_FLAG'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[SEASON_ID]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'SEASON_ID'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[START_PERIOD]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'START_PERIOD'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[START_THRESHOLD]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'START_THRESHOLD'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[TOLERANCE_PERCENT]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'TOLERANCE_PERCENT'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[USE_AUTO_PROJ_PERCENT]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'USE_AUTO_PROJ_PERCENT'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[USER1]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'USER1'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[USER2]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'USER2'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[USER3]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'USER3'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[USER4]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'USER4'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[VALIDATE_CRITERIA]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'VALIDATE_CRITERIA'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[VALIDATE_LEVEL]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'VALIDATE_LEVEL'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[VEHICLE_ID]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'VEHICLE_ID'
GO
EXEC sp_addextendedproperty N'MS_SSMA_SOURCE', N'TablesTemp.[F21_FMKT_OFFER].[VERTICAL]', 'SCHEMA', N'dbo', 'TABLE', N'F21_FMKT_OFFER', 'COLUMN', N'VERTICAL'
GO
