CREATE TABLE [dbo].[F21_FMSH_ITEM_MASTER]
(
[COMPANY_ID] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SKU] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DESCRIPTION] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ALTERNATE_SKU] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRODUCT_GROUP_ID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUB_PRODUCT_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SKU_STATUS] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PRODUCT_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DESCRIPTOR1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DESCRIPTOR2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DESCRIPTOR3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UOM] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOT_SIZE] [numeric] (18, 0) NULL,
[COST_EA] [numeric] (10, 4) NULL,
[STD_PRICE_EA] [numeric] (10, 4) NULL,
[DEFAULT_MIX_PERCENT] [numeric] (6, 4) NULL,
[STD_COST_EA] [numeric] (10, 4) NULL,
[SUB_CATEGORY_ID] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STD_LEAD_TIME] [numeric] (3, 0) NULL,
[CATEGORY_ID] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEFAULT_VENDOR_ID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BUYER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCHEDULER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRODUCT_ENGINEER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PLANNING_HORIZON] [numeric] (4, 0) NULL,
[CREATED_DATETIME] [datetime2] NULL,
[ITEM_TYPE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHANGE_FLAG] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_UPDATED_DATETIME] [datetime2] NULL,
[LAST_UPDATED_BY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SAFETY_STOCK_METHOD] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SAFETY_STOCK_LEVEL] [numeric] (8, 0) NULL,
[SAFETY_STOCK_FACTOR] [numeric] (8, 0) NULL,
[CLASSIFICATION_CODE] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IMMED_CANCEL_PERCENT] [numeric] (6, 4) NULL,
[BACKORDER_CURVE_ID] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RETURN_PERCENT] [numeric] (6, 4) NULL,
[RESELL_RETURN_PERCENT] [numeric] (6, 4) NULL,
[RETURNS_CURVE_ID] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MS_CALC_FLAG] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DROP_SHIP_FLAG] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLASS_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTOMIZATION_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WEIGHT] [numeric] (8, 4) NULL,
[LENGTH] [numeric] (5, 2) NULL,
[WIDTH] [numeric] (5, 2) NULL,
[DEPTH] [numeric] (5, 2) NULL,
[INVENTORY_VARIANCE_EA] [numeric] (10, 4) NULL,
[DIRECT_LABOR_EA] [numeric] (10, 4) NULL,
[USER1] [float] NULL,
[USER2] [float] NULL,
[USER3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER5] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER6] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER7] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER8] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEFAULT_WAREHOUSE_ID] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IMPORT_FLAG] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[REPRESENTATIVE_AGENCY] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UPC_CODE] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SECOND_SAMPLE_LETTER_FLAG] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PIF_SENT_DATE] [datetime2] NULL,
[PIF_RECD_DATE] [datetime2] NULL,
[DIRECT_SHIP_COST_EA] [numeric] (10, 4) NULL,
[ADDITIONAL_COST_EA] [numeric] (10, 4) NULL,
[AGENT_FEES_EA] [numeric] (10, 4) NULL,
[DUTY_FEES_EA] [numeric] (10, 4) NULL,
[FREIGHT_FEES_EA] [numeric] (10, 4) NULL,
[ADDITIONAL_SHIP_COST_EA] [numeric] (10, 4) NULL,
[SHIP_METHOD_CODE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FLOWDOWN_FLAG] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WORK_ORDER_FLAG] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NEVER_OUT_FLAG] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CS_DESCRIPTOR1] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CS_DESCRIPTOR2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CS_DESCRIPTOR3] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SH_COST_EA] [numeric] (8, 4) NULL,
[SH_REVENUE_EA] [numeric] (8, 4) NULL,
[BAD_DEBT_PERCENT] [numeric] (6, 6) NULL,
[VARIABLE_COST_PERCENT] [numeric] (6, 6) NULL,
[RETURNS_PERCENT] [numeric] (6, 6) NULL,
[RETURN_SH_COST_EA] [numeric] (8, 4) NULL,
[RETURN_SH_REVENUE_EA] [numeric] (8, 4) NULL,
[EXCESS_COST_EA] [numeric] (8, 4) NULL,
[BACKORDER_COST_EA] [numeric] (8, 4) NULL,
[RETURNS_PROCESSING_COST_EA] [numeric] (8, 4) NULL,
[ADMIN_COST_EA] [numeric] (8, 4) NULL,
[PLANT_VAR_COST_EA] [numeric] (8, 4) NULL,
[PLANT_VAR_LABOR_COST_EA] [numeric] (8, 4) NULL,
[ORDER_PROCESSING_COST_EA] [numeric] (8, 4) NULL,
[FACILITY_COST_EA] [numeric] (8, 4) NULL,
[CREDIT_COST_EA] [numeric] (8, 4) NULL,
[ONE_TIME_BUY_FLAG] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TOTAL_PZ_COST] [numeric] (12, 4) NULL,
[INVENTORY_VARIANCE_PCT] [numeric] (7, 6) NULL,
[DIRECT_LABOR_PCT] [numeric] (7, 6) NULL,
[DIRECT_SHIP_COST_PCT] [numeric] (7, 6) NULL,
[ADDITIONAL_COST_PCT] [numeric] (7, 6) NULL,
[AGENT_FEES_PCT] [numeric] (7, 6) NULL,
[DUTY_FEES_PCT] [numeric] (7, 6) NULL,
[FREIGHT_FEES_PCT] [numeric] (7, 6) NULL,
[FACILITY_COST_PCT] [numeric] (7, 6) NULL,
[SH_REVENUE_PCT] [numeric] (7, 6) NULL,
[RETURN_SH_COST_PCT] [numeric] (7, 6) NULL,
[RETURN_SH_REVENUE_PCT] [numeric] (7, 6) NULL,
[EXCESS_COST_PCT] [numeric] (7, 6) NULL,
[RETURN_PROCESSING_COST_PCT] [numeric] (7, 6) NULL,
[ADMIN_COST_PCT] [numeric] (7, 6) NULL,
[PLANT_VAR_COST_PCT] [numeric] (7, 6) NULL,
[PLANT_VAR_LABOR_COST_PCT] [numeric] (7, 6) NULL,
[ORDER_PROCESSING_COST_PCT] [numeric] (7, 6) NULL,
[CREDIT_COST_PCT] [numeric] (7, 6) NULL,
[BACKORDER_COST_PCT] [numeric] (7, 6) NULL,
[SH_COST_PCT] [numeric] (7, 6) NULL,
[VENTURE_HIERARCHY] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VENTURE_PH_NODE_ID] [float] NULL,
[BRAND] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LIQUIDATION_CODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OTHER_CANCEL_PCT] [numeric] (6, 6) NULL,
[DEFAULT_IMAGE_ID] [float] NULL,
[SS_SERVICE_LEVEL_PCT] [numeric] (7, 6) NULL,
[SS_FORECAST_VARIANCE_PCT] [numeric] (7, 6) NULL,
[FIRST_SALE_DATE] [datetime2] NULL,
[NO_WEEKS_OF_HISTORY] [float] NULL,
[CS_D1_SORT_ORDER] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CS_D2_SORT_ORDER] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CS_D3_SORT_ORDER] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CS_D1_DESCRIPTION] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CS_D2_DESCRIPTION] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CS_D3_DESCRIPTION] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEFAULT_COST_FLAGS] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CREATION_DATE] [datetime2] NULL
) ON [PRIMARY]
GO
